spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${env.DB_URL}:${env.DB_PORT}/${env.DB_NAME}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jda:
  token: ${env.JDA_TOKEN}

constants:
  respectUserId: ${env.RESPECT_USER_ID}
  goodManId: ${env.GOOD_MAN_ID}