spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jda:
  token: ${JDA_TOKEN}

constants:
  salaryRoleId: ${SALARY_ROLE_ID}
  respectUserId: ${RESPECT_USER_ID}
  goodManId: ${GOOD_MAN_ID}